- id: doi:10.1075/jsls.22006.cro
  image: https://www.jbe-platform.com/images/covers/25423843.png
  repo: langdonholmes/lexical_analysis
  extra-links:
    - type: journal
      link: https://www.jbe-platform.com/content/journals/10.1075/jsls.22006.cro
    - type: source
      link: https://github.com/langdonholmes/lexical_analysis

- id: doi:10.1007/978-981-19-5240-1_12
  image: https://media.springernature.com/full/springer-static/cover-hires/book/978-3-319-63673-3?as=webp
  extra-links:
    - type: journal
      link: https://link.springer.com/chapter/10.1007/978-981-19-5240-1_12
    - type: preprint
      link: https://zenodo.org/record/7262351
    - type: source
      link: https://github.com/aialoe/de-identification


- id: doi:10.3758/s13428-022-01797-5
  image: https://media.springernature.com/w184/springer-static/cover/journal/13428.jpg
  extra-links:
    - type: journal
      link: https://link.springer.com/article/10.3758/s13428-022-01797-5

- id: doi:10.1016/j.asw.2022.100667
  image: https://ars.els-cdn.com/content/image/1-s2.0-S1075293522X00044-cov200h.gif
  extra-links:
    - type: journal
      link: https://www.sciencedirect.com/science/article/pii/S1075293522000630

- id: doi:10.3758/s13428-022-01802-x
  image: https://media.springernature.com/w184/springer-static/cover/journal/13428.jpg
  extra-links:
    - type: journal
      link: https://link.springer.com/article/10.3758/s13428-022-01802-x


- id: doi:10.1007/s11145-021-10221-x
  image: https://media.springernature.com/w184/springer-static/cover/journal/11145.jpg
  extra-links:
    - type: journal
      link: https://link.springer.com/article/10.1007/s11145-021-10221-x

- id: doi:10.1177/02655322211060076
  image: https://journals.sagepub.com/na101/home/literatum/publisher/sage/journals/content/ltja/2022/ltja_39_4/ltja_39_4/20220924-01/ltja_39_4.largecover.png
  extra-links:
    - type: journal
      link: https://journals.sagepub.com/doi/abs/10.1177/02655322211060076

- id: doi:10.1007/s11145-021-10229-3
  image: https://media.springernature.com/w184/springer-static/cover/journal/11145.jpg
  extra-links:
    - type: journal
      link: https://link.springer.com/article/10.1007/s11145-021-10229-3

- id: doi:10.1126/sciadv.abj2836
  image: https://www.science.org/cms/asset/27a4c474-de32-4277-a1c9-5afb8f1cbc1f/sciadv.2021.7.issue-51.largecover.jpg
  extra-links:
    - type: journal
      link: https://www.science.org/doi/full/10.1126/sciadv.abj2836

- id: doi:10.1177/00222194221081473
  image: https://journals.sagepub.com/na101/home/literatum/publisher/sage/journals/content/ldxa/2023/ldxa_56_1/ldxa_56_1/20221209/ldxa_56_1.largecover.png
  extra-links:
    - type: journal
      link: https://journals.sagepub.com/doi/abs/10.1177/00222194221081473

- id: doi:10.37514/JWA-J.2022.6.1.04
  image: https://wac.colostate.edu/docs/jwa/cover-current.jpg
  extra-links:
    - type: journal
      link: https://wac.colostate.edu/docs/jwa/vol6/crossley-kim.pdf

- id: doi:10.17239/jowr-2022.14.01.01
  image: https://oaji.net/images/journals/small/2016/file1453363070.jpg
  extra-links:
    - type: journal
      link: https://www.jowr.org/index.php/jowr/article/view/831

- id: doi:10.1080/13670050.2020.1838434
  image: https://www.tandfonline.com/action/showCoverImage?doi=10.1080/rbeb20.v025.i06
  extra-links:
    - type: journal
      link: https://www.tandfonline.com/doi/abs/10.1080/13670050.2020.1838434?journalCode=rbeb20

- id: doi:10.1037/tmb0000063
  image: https://resize-v3.pubpub.org/eyJidWNrZXQiOiJhc3NldHMucHVicHViLm9yZyIsImtleSI6ImJvbW93ZDM2LzMxNjA5ODY0MjAyMzY0LnBuZyIsImVkaXRzIjp7InJlc2l6ZSI6eyJoZWlnaHQiOjIwMCwiZml0IjoiaW5zaWRlIiwid2l0aG91dEVubGFyZ2VtZW50Ijp0cnVlfX19
  extra-links:
    - type: journal
      link: https://tmb.apaopen.org/pub/kfxfdnk5/release/1

- id: doi:10.1016/j.jbi.2020.103658
  image: https://ars.els-cdn.com/content/image/1-s2.0-S1532046420X00128-cov200h.gif
  extra-links:
    - type: journal
      link: https://www.sciencedirect.com/science/article/pii/S1532046420302860
    - type: preprint
      link: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8186847/
