- id: doi:10.1075/jsls.22006.cro
  image: https://www.jbe-platform.com/images/covers/25423843.png
  repo: langdonholmes/lexical_analysis
  extra-links:
    - type: journal
      link: https://www.jbe-platform.com/content/journals/10.1075/jsls.22006.cro
    - type: source
      link: https://github.com/langdonholmes/lexical_analysis

- id: doi:10.1007/978-981-19-5240-1_12
  image: https://media.springernature.com/full/springer-static/cover-hires/book/978-3-319-63673-3?as=webp
  extra-links:
    - type: journal
      link: https://link.springer.com/chapter/10.1007/978-981-19-5240-1_12
    - type: preprint
      link: https://zenodo.org/record/7262351
    - type: source
      link: https://github.com/aialoe/de-identification

- id: doi:10.3758/s13428-022-01797-5
  image: https://media.springernature.com/w184/springer-static/cover/journal/13428.jpg
  extra-links:
    - type: journal
      link: https://link.springer.com/article/10.3758/s13428-022-01797-5

- id: doi:10.1016/j.asw.2022.100667
  image: https://ars.els-cdn.com/content/image/1-s2.0-S1075293522X00044-cov200h.gif
  extra-links:
    - type: journal
      link: https://www.sciencedirect.com/science/article/pii/S1075293522000630

- id: doi:10.3758/s13428-022-01802-x
  image: https://media.springernature.com/w184/springer-static/cover/journal/13428.jpg
  extra-links:
    - type: journal
      link: https://link.springer.com/article/10.3758/s13428-022-01802-x

- id: doi:10.1007/s11145-021-10221-x
  image: https://media.springernature.com/w184/springer-static/cover/journal/11145.jpg
  extra-links:
    - type: journal
      link: https://link.springer.com/article/10.1007/s11145-021-10221-x

- id: doi:10.1177/02655322211060076
  image: https://journals.sagepub.com/na101/home/literatum/publisher/sage/journals/content/ltja/2022/ltja_39_4/ltja_39_4/20220924-01/ltja_39_4.largecover.png
  extra-links:
    - type: journal
      link: https://journals.sagepub.com/doi/abs/10.1177/02655322211060076

- id: doi:10.1007/s11145-021-10229-3
  image: https://media.springernature.com/w184/springer-static/cover/journal/11145.jpg
  extra-links:
    - type: journal
      link: https://link.springer.com/article/10.1007/s11145-021-10229-3

- id: doi:10.1126/sciadv.abj2836
  image: https://www.science.org/cms/asset/27a4c474-de32-4277-a1c9-5afb8f1cbc1f/sciadv.2021.7.issue-51.largecover.jpg
  extra-links:
    - type: journal
      link: https://www.science.org/doi/full/10.1126/sciadv.abj2836

- id: doi:10.1177/00222194221081473
  image: https://journals.sagepub.com/na101/home/literatum/publisher/sage/journals/content/ldxa/2023/ldxa_56_1/ldxa_56_1/20221209/ldxa_56_1.largecover.png
  extra-links:
    - type: journal
      link: https://journals.sagepub.com/doi/abs/10.1177/00222194221081473

- id: doi:10.37514/JWA-J.2022.6.1.04
  image: https://wac.colostate.edu/docs/jwa/cover-current.jpg
  extra-links:
    - type: journal
      link: https://wac.colostate.edu/docs/jwa/vol6/crossley-kim.pdf

- id: doi:10.17239/jowr-2022.14.01.01
  image: https://oaji.net/images/journals/small/2016/file1453363070.jpg
  extra-links:
    - type: journal
      link: https://www.jowr.org/index.php/jowr/article/view/831

- id: doi:10.1080/13670050.2020.1838434
  image: https://www.tandfonline.com/action/showCoverImage?doi=10.1080/rbeb20.v025.i06
  extra-links:
    - type: journal
      link: https://www.tandfonline.com/doi/abs/10.1080/13670050.2020.1838434?journalCode=rbeb20

- id: doi:10.1037/tmb0000063
  image: https://resize-v3.pubpub.org/eyJidWNrZXQiOiJhc3NldHMucHVicHViLm9yZyIsImtleSI6ImJvbW93ZDM2LzMxNjA5ODY0MjAyMzY0LnBuZyIsImVkaXRzIjp7InJlc2l6ZSI6eyJoZWlnaHQiOjIwMCwiZml0IjoiaW5zaWRlIiwid2l0aG91dEVubGFyZ2VtZW50Ijp0cnVlfX19
  extra-links:
    - type: journal
      link: https://tmb.apaopen.org/pub/kfxfdnk5/release/1

- id: doi:10.1016/j.jbi.2020.103658
  image: https://ars.els-cdn.com/content/image/1-s2.0-S1532046420X00128-cov200h.gif
  extra-links:
    - type: journal
      link: https://www.sciencedirect.com/science/article/pii/S1532046420302860
    - type: preprint
      link: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8186847/

- id: doi:10.1093/jamia/ocaa281
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/jamia/Issue/28/6/1/m_jaminfo_28_6cover.jpeg?Expires=1674788390&Signature=mVWCrJ8UAgCEVaDfJX0M5XqT6Qfy6cpjueyZvXDxKHr~~HQ75zwAWlfpKZV9zs4ajSZbMFku7Ca2OOin5vL5t-7O2YaWhrQO2h6HmyDM6Y3F32~Ff1RP1PpFoeDEqT7EIiijM2UfWmOVyDWi0RY-wQvuOPopLB0qXiJNYILZIXgeH-CKiVt2qA9sGbUi4aCnSWqLkM6Ms9tIa~X89AmKulJ~82XSqTkExKxPuU4yrpREc2SrJEWQpHSdIPDVumhVPv2yMiOS47Y6SdJelJdaLfqA-oWZJwg7o8bzS4OAauVfgvuM-kcqh-uKgOzuAWWO3Hc0mx~CGBpGP6W~TsjeqA__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  extra-links:
    - type: journal
      link: https://academic.oup.com/jamia/article-abstract/28/6/1252/6000399?redirectedFrom=fulltext&login=false#no-access-message
    - type: preprint
      link: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8200267/

- id: doi:10.1080/10410236.2020.1731781
  image: https://www.tandfonline.com/na101/home/literatum/publisher/tandf/journals/content/hhth20/2023/hhth20.v038.i01/hhth20.v038.i01/20221212-01/hhth20.v038.i01.cover.jpg
  extra-links:
    - type: journal
      link: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7483831/

- id: doi:10.1016/j.jslw.2021.100824
  image: https://ars.els-cdn.com/content/image/1-s2.0-S1060374321X00045-cov150h.gif
  extra-links:
    - type: journal
      link: https://www.sciencedirect.com/science/article/pii/S1060374321000394

- id: doi:10.1080/15434303.2020.1844205
  image: https://www.tandfonline.com/action/showCoverImage?doi=10.1080/hlaq20.v018.i02
  extra-links:
    - type: journal
      link: https://www.tandfonline.com/doi/abs/10.1080/15434303.2020.1844205

- id: doi:10.1017/S0272263120000546
  image: https://static.cambridge.org/covers/SLA_0_0_0/studies-in-second-language-acquisition.jpg
  extra-links:
    - type: journal
      link: https://www.cambridge.org/core/journals/studies-in-second-language-acquisition/article/abs/measuring-longitudinal-writing-development-using-indices-of-syntactic-complexity-and-sophistication/23CFFB4579D110AB0ED96C74990989C3
    - type: preprint
      link: https://pure.rug.nl/ws/portalfiles/portal/187076402/measuring_longitudinal_writing_development_using_indices_of_syntactic_complexity_and_sophistication.pdf

- id: doi:10.1111/ijal.12358
  image: https://onlinelibrary.wiley.com/cms/asset/e50959e5-d62f-4b93-b21b-719af23c758a/ijal.v31.3.cover.jpg
  extra-links:
    - type: journal
      link: https://onlinelibrary.wiley.com/doi/abs/10.1111/ijal.12358

- id: doi:10.1353/hpu.2021.0067
  image: https://muse.jhu.edu/issue/44396/image/front_cover.jpg?format=180
  extra-links:
    - type: journal
      link: https://muse.jhu.edu/article/789674

- id: doi:10.1111/1475-6773.13560
  image: https://onlinelibrary.wiley.com/cms/asset/9b1e3ed1-3b83-463e-8ea4-d7a94b7807ee/hesr.v56.1.cover.jpg
  extra-links:
    - type: journal
      link: https://onlinelibrary.wiley.com/doi/full/10.1111/1475-6773.13560

- id: doi:10.17239/jowr-2020.11.03.01
  image: https://oaji.net/images/journals/small/2016/file1453363070.jpg
  extra-links:
    - type: journal
      link: https://www.jowr.org/index.php/jowr/article/view/582
