- id: doi:10.1075/jsls.22006.cro
  image: https://benjamins.com/covers/3d_flat_225x300/jsls.5.2.pb.png
  repo: langdonholmes/lexical_analysis
  extra-links:
    - type: journal
      link: https://www.jbe-platform.com/content/journals/10.1075/jsls.22006.cro
    - type: source
      link: https://github.com/langdonholmes/lexical_analysis

- id: doi:10.1007/978-981-19-5240-1_12
  image: https://media.springernature.com/full/springer-static/cover-hires/book/978-3-319-63673-3?as=webp
  extra-links:
    - type: journal
      link: https://link.springer.com/chapter/10.1007/978-981-19-5240-1_12
    - type: preprint
      link: https://zenodo.org/record/7262351
    - type: source
      link: https://github.com/aialoe/de-identification
